version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: pds-postgres-e-commerce
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ecomuser
      POSTGRES_PASSWORD: ecomuser123
      POSTGRES_DB: e_commerce_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest
    container_name: pds-minio-e-commerce
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio@123
      MINIO_DEFAULT_BUCKETS: ecommerce
    volumes:
      - minio_data:/data

volumes:
  postgres-data:
    driver: local
  minio_data:
    driver: local
